# Generated by Django 3.0.5 on 2021-05-09 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_marks', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=10)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercoin_created_user', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercoin_updated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='points',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='event',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(default='default.png', upload_to='event_category/'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(default='default.png', upload_to='event_image/'),
        ),
        migrations.DeleteModel(
            name='EventJobCategoryLinking',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='UserCoin',
        ),
    ]
